### ISSUE TITLE
missing tutorial style like updated introduction

### ISSUE THREAD

**Issue by v217** [matijapretnar/eff#13]
There is no tutorial/overview comparing the advantages of eff to other ways of describing IO in Ocaml. This would be helpful to discuss the advantages.

**Comment by matijapretnar** [comment]
I know this is a bit late, but we now have a (semi-documented) interactive tutorial at www.eff-lang.org/try/

**Comment by b21e** [comment]
Great! Thanks!

**Comment by matijapretnar** [comment]
The `examples` folder has now been updated and expanded with more comments. Additionally `jseff/examples.eff` is organized like a small tutorial to Eff.
