### ISSUE TITLE
Does not compile on OS X

### ISSUE THREAD

**Issue by andrejbauer** [matijapretnar/eff#17]
Here is my Opam setup:

    $ env | grep opam
    CAML_LD_LIBRARY_PATH=/usr/local/opam/4.01.0/lib/stublibs
    MANPATH=/usr/local/opam/4.01.0/man:
    PERL5LIB=/usr/local/opam/4.01.0/lib/perl5
    OPAMROOT=/usr/local/opam
    OCAML_TOPLEVEL_PATH=/usr/local/opam/4.01.0/lib/toplevel
    PATH=/usr/local/opam/4.01.0/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/andrej/bin:/Users/andrej/.cabal/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin

I am on master branch of Eff, commit 5ad3b545324413765c7d42fa4994fcccfb573c02.
When I run `./configure` it gets wrong the directory in which Ocaml binaries are found:

    $ ./configure 
    Configuration: 
    ocamlfind: ........................................... /usr/local/opam/system/bin/ocamlfind
    ocamlc: .............................................. /usr/local/bin/ocamlc.opt
    ocamlopt: ............................................ /usr/local/bin/ocamlopt.opt
    ocamlbuild: .......................................... /usr/local/bin/ocamlbuild

And so compilation fails:

    $ make
    ocaml setup.ml -build 
    Finished, 1 target (0 cached) in 00:00:00.
    /bin/sh: /usr/local/opam/system/bin/ocamlfind: No such file or directory
    Failure: Error while running: /usr/local/opam/system/bin/ocamlfind list.
    Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
    E: Failure("Command ''/usr/local/bin/ocamlbuild' src/eff.native -tag debug' terminated with error code 2")
    make: *** [build] Error 1

**Comment by matijapretnar** [comment]
Did you try to remove `setup.data` and rerun `./configure`? I think I had to run it twice for it to reflect the current state of OPAM.

**Comment by andrejbauer** [comment]
I cannot reproduce the problem anymore. Something in opam got updated, apparently.
