### ISSUE TITLE
Compile error when installing with OPAM

### ISSUE THREAD

**Issue by walkie** [matijapretnar/eff#25]
I get the following error when attempting to install Eff via OPAM on macOS.

~~~
# File "src/parsing/lexer.mll", line 62, characters 36-37:
# Error: This expression has type string but an expression was expected of type
#          bytes
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/Users/walkie/.opam/system/bin/ocamlbuild' src/eff.native -tag debug' terminated with error code 10")
# make: *** [build] Error 1
~~~

Here's the full output of OPAM, which includes the versions of dependencies: [OPAM-Eff.txt](https://github.com/matijapretnar/eff/files/1463609/OPAM-Eff.txt)

**Comment by matijapretnar** [comment]
Thanks for letting me know. I'll look at this as soon as possible.

**Comment by matijapretnar** [comment]
@walkie: Fixed - thanks again for noticing it!
