### ISSUE TITLE
Make syntax compatible with Multicore OCaml

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/eff#34]
Ignoring 372 variants (see #30) of Eff floating around, both Eff and Multicore OCaml both offer algebraic effects and handlers with slightly different syntax. I guess there is no syntax so brilliant that it would outweigh the convenience of just taking one source code and putting it into the other language. Since Multicore OCaml is the bigger one here, I suggest Eff adopts their syntax. The necessary changes are

- [x] declare operations with `effect Eff : ...` - we did this some time ago
- [ ] call operations with `perform (Eff x)` rather than `#Eff x` - in the long run, we'd also want `perform EffWithNoArgs` and need the type `'a eff`, but in the short run, this just needs some slight changes in the parser
- [ ] resume continuations with `continue k x` rather than `k x` - I don't want to make a distinction between functions and continuations, so I suggest to define `continue` as the identity function
- [ ] define handling clauses inside a match statement

I don't know whether to keep the old syntax for handlers or not, but maybe I'd issue a warning if it is used as it will make the code incompatible with Multicore OCaml. I would do the same if someone forgot to write `continue` when resuming the continuation. There will always be incompatibilities because OCaml offers so much other stuff, but at least this will give us some guarantees for small effectful examples.

@kayceesrk, @lpw25 - What do you think and did I miss anything?

**Comment by lpw25** [comment]
I think you might want to hold off on some of this for a bit. We're looking towards moving multicore OCaml over to structural typed effects, which obviously will change some of the syntax (e.g. we wouldn't have operation declarations anymore).

Adding support for handling clauses inside a match statement seems like the most important one for making examples transferable. The rest can probably be done with `sed`.

**Comment by matijapretnar** [comment]
Long time no see @lpw25 - happy to be back in touch!

@kayceesrk told me about structural effects - I think it is a good choice (see page 14 of https://arxiv.org/pdf/1605.06938.pdf for example) and was also thinking of adding them in the long run.

In this case, do you plan to remove operation declarations, or do you intend to keep it for e.g. built-in effects?

**Comment by lpw25** [comment]
(Sorry for the slow reply)

I plan to remove operation declarations.

**Comment by matijapretnar** [comment]
@zigaLuksic, @andrejbauer: I guess if we change the syntax of Eff 4.0, we shouldn't call it Eff 4.1 but Eff 5.0?

**Comment by zigaLuksic** [comment]
Any meaningful program written in Eff 4.0 won't work after this change (as it changes the syntax of a major component of the language), so maybe calling it Eff 5.0 is a better idea.
