### ISSUE TITLE
What is the syntax for returning a tuple 

### ISSUE THREAD

**Issue by alkubaig** [matijapretnar/eff#35]
I am trying to do an effect that returns a tuple 
but I am not able to figure out the syntax 

`effect Choice : unit -> (string, bool);;
`
Previously, I had something like 

```
type 'a choice = effect
  operation findChoice : unit -> 'a
end;;
```

but with the new syntax, I am not able to pass 'a 

I appreciate your help 

Thanks,

**Comment by zigaLuksic** [comment]
Try the type string*bool for the tuple type

**Comment by alkubaig** [comment]
worked! 

Thank you so much!
