### ISSUE TITLE
Eff compilation error

### ISSUE THREAD

**Issue by alkubaig** [matijapretnar/eff#40]
Hello all, 

Are there new instructions for compilation? 

I am having some compilation errors 

```make

ocaml setup.ml -build 
+ ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package js_of_ocaml.ocamlbuild myocamlbuild.ml /usr/local/Cellar/ocamlbuild/0.12.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind: Package `js_of_ocaml.ocamlbuild' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/usr/local/bin/ocamlbuild' src/eff.native -use-ocamlfind -plugin-tags 'package(js_of_ocaml.ocamlbuild)' -tag debug' terminated with error code 10")
make: *** [build] Error 1
```

**Comment by zigaLuksic** [comment]
Some new packages are needed.
If you are using OPAM just install the missing packages with `opam install js_of_ocaml` and do the same for 
other packages that it complains about. 
Also try using `make clean distclean` as it deals with some problems.

**Comment by alkubaig** [comment]
worked!
Thanks

**Comment by zigaLuksic** [comment]
Also, if you haven't noticed, Eff has been updated to Eff 5.0 with a minor change in syntax for defining and using types. I suggest you take another look at the examples or at the [online examples](http://www.eff-lang.org/try/) to see the current syntax.
