### ISSUE TITLE
Probability example is broken

### ISSUE THREAD

**Issue by ohad** [matijapretnar/eff#43]
Go to the [Try Eff](http://www.eff-lang.org/try/) page.
Go to the Probability example
Hit "Load File"

Expected behaviour: file loads successfully.
Actual behaviour:
```
Warning (line 11, char 19):
This pattern-matching is not exhaustive.
                                    Here is an example of a value that is not matched:
val uniform : 'a list -> 'a = <fun>
Typing error (line 22, char 16):
Unbound operation Random_float
# 
 
```

**Comment by matijapretnar** [comment]
Whoops! Fixed in 506c681cbde18689480877a51bccac79b34065fc.
