### ISSUE TITLE
Loaded code and code displayed are different?

### ISSUE THREAD

**Issue by spavikevik** [matijapretnar/eff#58]
In the Non-determinism example on the website, the backtrack handler code is written like this
```ocaml
let backtrack = handler
  | effect Decide k ->
    (* We use a second handler to handle the continuation. *)
    handle continue k false with
    | effect Fail _ -> continue k true
;;
```

However, it seems to me, that the paper defines it like follows
```ocaml
let backtrack = handler
  | effect Decide k ->
    (* We use a second handler to handle the continuation. *)
    handle continue k true with
    | effect Fail _ -> continue k false
;;
```

_Notice that the continuations are reversed_

When I try loading the code in the REPL, the handler behaves correctly (I believe), even though the code shown above the REPL is wrong.

I am not sure whether this is a misunderstanding on my side or a bug, but I would be appreciative if someone could take a look at it.

**Comment by spavikevik** [comment]
On a second look, I didn't notice that backtrack is later overriden in the code...

**Comment by matijapretnar** [comment]
Hmmm, the second definition was probably unintentional, so I removed it. Thanks!
