### ISSUE TITLE
JSON database implementation and conversions

### ISSUE THREAD

**Issue by Shady-Morsi** [matijapretnar/eff#79]
Does EFF support for JSON conversions. This includes converting files/strings/classes to dictionaries; and dictionaries to json formatted strings ?

**Comment by matijapretnar** [comment]
No, Eff does not support JSON, neither does it support files, dictionaries, or classes. Did you have any particular application in mind that needs JSON?

**Comment by Shady-Morsi** [comment]
not really but i was curious since OCaml [has a JSON library ](https://github.com/ocaml-community/yojson) aswell you can parse JSON with OCaml

**Comment by matijapretnar** [comment]
Ah, no, given the limited resources, we keep Eff minimal and develop only features that make interesting combinations with algebraic effects.
